---
title: "Classification Tree"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading in data and splitting into test and train
```{r}
library(tidyverse)
library(rpart)
library(randomForest)
library(tree)
library(rpart.plot)
library(rattle)
set.seed(1)
#Disc Distance
tree_data <- processed_data[,c(28,65,86,88,180:191,196,197,199:203)]
#Cont Distance
# tree_data <- processed_data[,c(28,65,86,88,180:197,199)]
col_names <- names(tree_data)
tree_data[,col_names] <- lapply(tree_data[,col_names] , factor)

#Cont Distance
# tree_data[,17] <- as.integer(tree_data[,17])
# tree_data[,18] <- as.integer(tree_data[,18])
# tree_data[,19] <- as.integer(tree_data[,19])
# tree_data[,20] <- as.integer(tree_data[,20])


train_ind <- sample(30491, 24393)
tree_train <- tree_data[train_ind,]
tree_test <- tree_data[-train_ind,]
```

Full tree, no pruning
```{r, fig.height=20, fig.width=20}
full_tree <- rpart(as.factor(Label) ~ ., data = tree_train, method = "class", xval = 10, cp = .001)

class_pred_ft <- table(predict(full_tree, type="class", newdata = tree_test), tree_test$Label)
test_error_ft <- 1-sum(diag(class_pred_ft))/sum(class_pred_ft)
```


Pruned Tree
```{r, fig.height=10, fig.width=10}
pruned_tree <- rpart(as.factor(Label) ~ ., data = tree_train, method = "class", xval = 10, cp = .0044)

# printcp(pruned_tree)
# plotcp(pruned_tree)
# summary(pruned_tree)

class_pred_pt <- table(predict(pruned_tree, type="class", newdata = tree_test), tree_test$Label)
test_error_pt <- 1-sum(diag(class_pred_pt))/sum(class_pred_pt)
```
Most Pruned
```{r, fig.height=10, fig.width=10}
prunedest_tree <- rpart(as.factor(Label) ~ ., data = tree_train, method = "class", xval = 10, cp = .015)

# printcp(pruned_tree)
# plotcp(pruned_tree)
# summary(pruned_tree)


class_pred_mpt <- table(predict(prunedest_tree, type="class", newdata = tree_test), tree_test$Label)
test_error_mpt <- 1-sum(diag(class_pred_mpt))/sum(class_pred_mpt)
```

Results

```{r, fig.height=10, fig.width=10}

fancyRpartPlot(full_tree, caption = "Full Tree", cex = .6)

jpeg(file="Shrinkage Tuning Full Tree.jpg")
plotcp(full_tree)
dev.off()


png(file="Prunned Tree.png", width = 750, height = 500)
fancyRpartPlot(pruned_tree, caption = "Pruned Tree", cex = .6)
dev.off()

jpeg(file="Shrinkage Tuning Pruned Tree.jpg")
plotcp(pruned_tree)
dev.off()

png(file="Prunnedest Tree.png", width = 1000, height = 600)
fancyRpartPlot(prunedest_tree, caption = "Pruned Tree", cex =1.4)
dev.off()

error_df <- data.frame(error = c(test_error_ft, test_error_pt, test_error_mpt),
                       TreeType = c("Full Tree", "Pruned Tree", "Most Pruned Tree"))

ggplot(data = error_df, aes(x = TreeType, y = error)) + 
  geom_bar(stat = "identity") + 
  scale_x_discrete(limits=c("Full Tree", "Pruned Tree", "Most Pruned Tree")) + 
  theme_minimal() + 
  labs(x = "Tree Type",
       y = "Test Error",
       title = "Test Error By Tree Type") + 
  ylim(0,.3) + 
  geom_text(aes(label=round(error,4)), vjust=1.6, color="white", size=6)

t(class_pred_ft)
t(class_pred_ft) / rowSums(t(class_pred_ft))

t(class_pred_pt)
t(class_pred_pt) / rowSums(t(class_pred_pt))

t(class_pred_mpt)
t(class_pred_mpt) / rowSums(t(class_pred_mpt))


 unique(pruned_tree$frame$var)
 unique(prunedest_tree$frame$var)
```