---
title: "NN"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rpart)
library(randomForest)
library(tree)
library(rpart.plot)
library(rattle)
set.seed(1)
#Disc Distance
tree_data <- processed_data[,c(28,65,86,88,146,180:183,185:191,196,197,199:203)]
label_ind <- 17

# #Cont Distance
# tree_data <- processed_data[,c(28,65,86,88,180:197,199)]
# label_ind <- 21

col_names <- names(tree_data)
tree_data[,col_names] <- lapply(tree_data[,col_names] , factor)

# # Cont Distance
# tree_data[,17] <- as.integer(tree_data[,17])
# tree_data[,18] <- as.integer(tree_data[,18])
# tree_data[,19] <- as.integer(tree_data[,19])
# tree_data[,20] <- as.integer(tree_data[,20])


train_ind <- sample(30491, 24393)
tree_train <- tree_data[train_ind,]
tree_test <- tree_data[-train_ind,]

tree_data[,label_ind] <- as.numeric(tree_data[,label_ind]) - 1
tree_train[,label_ind] <- as.numeric(tree_train[,label_ind]) - 1
tree_test[,label_ind] <- as.numeric(tree_test[,label_ind]) - 1
```


```{r}
library(keras)
set.seed(1)
model <- keras_model_sequential() %>%
  layer_dense(units = 64, activation = "relu", input_shape = c(22)) %>%
  layer_dense(units = 2, activation = "softmax") 

model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)

model %>% fit(x = data.matrix(tree_train[,-label_ind]),y = to_categorical(tree_train[,label_ind]), epochs=100, batch_size = 1024,
              validation_data=list(data.matrix(tree_test[,-label_ind]), to_categorical(tree_test[,label_ind])))

model %>% evaluate(data.matrix(tree_test[,-label_ind]),y = to_categorical(tree_test[,label_ind]), verbose = 1)

```

```{r}
library(keras)
set.seed(1)

#BEST MODEL

model <- keras_model_sequential() %>%
  layer_dense(units = 32, activation = "relu", input_shape = c(22)) %>%
  # layer_dropout(1/3) %>%
  layer_dense(units = 32, activation = "relu") %>% 
  layer_dense(units = 2, activation = "softmax") 

model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)

model %>% fit(x = data.matrix(tree_train[,-label_ind]),y = to_categorical(tree_train[,label_ind]), epochs=64, batch_size = 1024,
              validation_data=list(data.matrix(tree_test[,-label_ind]), to_categorical(tree_test[,label_ind])))

model %>% evaluate(data.matrix(tree_test[,-label_ind]),y = to_categorical(tree_test[,label_ind]), verbose = 1)


fnn_pred <- (predict(model,x = data.matrix(tree_test[,-label_ind]), type = "class") %>% apply(1,which.max)) - 1

t(table(fnn_pred, tree_test$Label))
t(t(table(fnn_pred, tree_test$Label))) / rowSums(t(t(table(fnn_pred, tree_test$Label))))
#8126

```

```{r}
set.seed(1)
model <- keras_model_sequential() %>%
  layer_dense(units = 128, activation = "relu", input_shape = c(22)) %>%
  layer_dense(units = 2, activation = "softmax") 

model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)

model %>% fit(x = data.matrix(tree_train[,-label_ind]),y = to_categorical(tree_train[,label_ind]), epochs=100, batch_size = 1024,
              validation_data=list(data.matrix(tree_test[,-label_ind]), to_categorical(tree_test[,label_ind])))

#test accuracu of .8185

```

```{r}
library(keras)
set.seed(1)

model <- keras_model_sequential() %>%
  layer_dense(units = 128, activation = "relu", input_shape = c(22)) %>%
  layer_dense(units = 128, activation = "sigmoid") %>% 
  layer_dense(units = 2, activation = "softmax") 

model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)

model %>% fit(x = data.matrix(tree_train[,-label_ind]),y = to_categorical(tree_train[,label_ind]), epochs=100, batch_size = 1024,
              validation_data=list(data.matrix(tree_test[,-label_ind]), to_categorical(tree_test[,label_ind])))



model %>% evaluate(data.matrix(tree_test[,-label_ind]),  to_categorical(tree_test[,label_ind]), verbose = 1)

```
